float:
  any:
  - base_args: ['@metric']
    constructor: PGVector
    disabled: false
    docker_tag: ann-benchmarks-pgvector-hnsw
    module: ann_benchmarks.algorithms.pgvector-hnsw
    name: pgvector-hnsw
    run_groups:
      pgvector:
        args: [[4, 20, 100]]
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
