float:
  any:
  - base_args: ['@metric']
    constructor: PGEmbedding
    disabled: false
    docker_tag: ann-benchmarks-pg_embedding_hnsw
    module: ann_benchmarks.algorithms.pg_embedding_hnsw
    name: pg_embedding_hnsw
    run_groups:
      pg_emb_hnsw:
        args: [[4, 20, 100]]
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
